### PR TITLE
the introduction of tests!

### PR DESCRIPTION
**Pull request by muneerahp**
thoughts welcome.

### CODE REVIEW

**Comment by drj11** [comment]
Since this works and is an improvement, I'm happy to merge this as-is.

There are minor niggles, but it's up to you if you want to fix those here or in a new PR. Let me know.

- requirements.txt validation can be left to CI.
- yes, should run tests in CI (that would make a good additonal PR)
- good to have the HTML in and the data out snapshotted as fixtures (maybe there is a `pytest` way to do fixtures, that's for both of us to find out);
- eval is BAD, replace with JSON (but in this case, because it is reading from a fixed file, I won't let it stop the PR merging);
- format with black (adding a check that `black` doesn't change the code, might be a good addition to CI).

**Comment by muneerahp** [comment]
Fixed the ones that seem good to fix before a merge (eval to json/black formatting), can handle the rest in a new PR. 

JSON  seems cleaner, so changed. 
I assume the issues with eval in general are security related, rather than "this will cause something different to happen across different systems" (it doesn't seem it will, any more so than code not run by eval at least)?

**Comment by drj11** [comment]
The empty `__init__.py` files are a bit annoying. But I don't know enough to remove them. More studying of https://github.com/pypa/sampleproject is possibly required.

**Comment by drj11** [comment]
thanks!

**Pull request merged**
