### PR TITLE
Adding Travis CI

### LINKED ISSUE #8: There is no continuous integration
Adding a Travis configuration file would be good.

If someone wants to try their hand at other Continuous Integration providers, that would be okay too!

### PR DESCRIPTION
**Pull request by midhun1998**
Fixes #8

### CODE REVIEW

**Comment by drj11** [comment]
The `.travis.yml` looks okay, but the PR has done something to the (formatting?) of the other files that have been marked as changed. I'll investigate.

**Comment by midhun1998** [comment]
Yes. My apologises. I guess the code editor made some minor formatting changes.

**Comment by drj11** [comment]
Can I force push to this branch, that would be the simplest way to fix this issue. After the force push you would be best off deleting your own clone and recloning.

**Comment by midhun1998** [comment]
Yes sounds good. 👍🏻

**Comment by drj11** [comment]
Great, thanks for the travis file! :)

**Pull request merged**
